# general settings
name: train_SwinIR_SRx2_scratch_P48W8_DIV2K_500k_B4G8
model_type: SwinIRModel
scale: 2
num_gpu: auto
manual_seed: 0

tile: # use the tile mode for limited GPU memory when testing.
  tile_size: 256 # the higher, the more utilized GPU memory and the less performance change against the full image. must be an integer multiple of the window size.
  tile_pad: 32 # overlapping between adjacency patches.must be an integer multiple of the window size.

# dataset and data loader settings
datasets:
  train:
    name: map600
    type: PairedImageDataset
#    dataroot_gt: datasets/DF2K/DIV2K_train_HR_sub
#    dataroot_lq: datasets/DF2K/DIV2K_train_LR_bicubic_X2_sub
#    meta_info_file: basicsr/data/meta_info/meta_info_DIV2K800sub_GT.txt
    dataroot_gt: datasets/map600/map_train_HR_sub
    dataroot_lq: datasets/map600/map_train_LR_bicubic/X2_sub
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: map10
    type: PairedImageDataset
    dataroot_gt: datasets/map600/map10/gt
    dataroot_lq: datasets/map600/map10/X2
    io_backend:
      type: disk

# network structures
network_g:
  type: SwinIR
  upscale: 2
  in_chans: 3
  img_size: 48
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
